package com.example.calories.utils;

import static com.example.calories.utils.Utility.clipData;
import static com.example.calories.utils.Utility.makeToast;

import android.content.Context;

import com.example.calories.data.models.Product;

import java.util.ArrayList;

public class SystemProducts_Utils {
    private static ArrayList<Product> SystemProductArr = new ArrayList<>();//רשימת מוצרים (מערכת)

    private static void makeTheList(){
        SystemProductArr = new ArrayList<>();
        //הכנסת איברים לרשימה
// הצעת לעשות רשימות של- פיצוחיםת משקאות אלכוהולים, מסיבת יומולדת, חטיפים(לפי חטיף בודד לא מארז (ביסל, במב,תפוצ,)), חגים למשל טו בשבט/ יום העצמאות, אוכל סיני, מנגל, שווארמיה מאפייה וכו.וכו

        SystemProductArr.add(new Product(0, "צ'וקטה קקאו - עוגה אישית במילוי קרם קקאו , Chocketa", "יחידה", "129", "7290018893869"));
        SystemProductArr.add(new Product(0, "צ'וקטה קקאו - עוגה אישית במילוי קרם קקאו , Chocketa", "100 גרם", "430", "7290018893661"));
        SystemProductArr.add(new Product(0, "עוגות אישיות קרם שוקולד , vinci", "יחידה", "145", "7296073346340"));
        SystemProductArr.add(new Product(0, "עוגות אישיות קרם שוקולד , vinci", "100 גרם", "414", "7296073346340"));
        SystemProductArr.add(new Product(0, "קינדר דליס / kinder delice עוגות אישיות , kinder", "יחידה", "193", "8000500267103"));
        SystemProductArr.add(new Product(0, "קינדר דליס / kinder delice עוגות אישיות , kinder", "100 גרם", "495", "8000500267103"));
        SystemProductArr.add(new Product(0, "מאפה דונאטס ללא גלוטן בטעם תות - ורוד", "יחידה", "175", "7290017040554 , 7290017040523"));
        SystemProductArr.add(new Product(0, "מאפה דונאטס ללא גלוטן בטעם תות - ורוד", "100 גרם", "474", "7290017040554"));
        SystemProductArr.add(new Product(0, "סנדוויץ פסטרמה עדן", "יחידה", "250", ""));
        SystemProductArr.add(new Product(0, "דובונים קטשופ", "100 גרם", "526", "7290106572614"));
        SystemProductArr.add(new Product(0, "דובונים קטשופ, אסם", "שקית", "211", "7290106572614"));
        SystemProductArr.add(new Product(0, "סלים דליס - לא גלוטן עם שוקולד חלב", "יחידה", "62", "7290105439178"));
        SystemProductArr.add(new Product(0, "סלים דליס - לא גלוטן עם שוקולד חלב", "100 גרם", "480", "7290105439178"));
        SystemProductArr.add(new Product(0, "ביצת הפתעה / ביצת קינדר, קינדר / kinder", "יחידה", "110", "8000500406069 , 80906056"));
        SystemProductArr.add(new Product(0, "ביצת הפתעה / ביצת קינדר, קינדר / kinder", "100 גרם", "552", "8000500406069 , 80906056"));
        SystemProductArr.add(new Product(0, "ג'וי / joy / ביצת קינדר , קינר Kinder", "יחידה", "110", "8000500028124 , 80310891"));
        SystemProductArr.add(new Product(0, "ג'וי / joy / ביצת קינדר , קינר Kinder", "100 גרם", "550", "8000500028124 , 80310891"));
        SystemProductArr.add(new Product(0, "קינמון טחון, תבלין", "קורט", "3", ""));
        SystemProductArr.add(new Product(0, "קינמון טחון, תבלין", "100 גרם", "247", ""));
        SystemProductArr.add(new Product(0, "סוכר חום", "כפית שטוחה", "27", ""));
        SystemProductArr.add(new Product(0, "סוכר חום", "כפית גדושה", "34", ""));
        SystemProductArr.add(new Product(0, "סוכר חום", "כף שטוחה", "65", ""));
        SystemProductArr.add(new Product(0, "סוכר חום", "כף גדושה", "72", ""));
        SystemProductArr.add(new Product(0, "סוכר חום", "כוס", "741", ""));
        SystemProductArr.add(new Product(0, "סוכר חום", "100 גרם", "380", ""));
        SystemProductArr.add(new Product(0, "קטשופ היינץ, היינץ /Heinz", "100 גרם", "102", "8410066140190"));
        SystemProductArr.add(new Product(0, "מיונז אמיתי, תלמה", "כף", "90", "7290000111186"));
        SystemProductArr.add(new Product(0, "מיונז אמיתי, תלמה", "100 גרם", "600", "7290000111186"));
        SystemProductArr.add(new Product(0, "לחם ללא גלוטן, מיקסוי ישראל בעמ", "פרוסה", "65", ""));
        SystemProductArr.add(new Product(0, "לחם ללא גלוטן, מיקסוי ישראל בעמ", "100 גרם", "218", ""));
        SystemProductArr.add(new Product(0, "ופלים משובחים בטעם שוקולד, מן", "100 גרם", "518", "7290000311203"));
        SystemProductArr.add(new Product(0, "חטיפי חלוה וניל קאו אגוזים, אחווה (יש לערוך)", "100 גרם", "550", "7290000572673"));
        SystemProductArr.add(new Product(0, "חטיפי חלוה וניל קאו אגוזים, אחווה (יש לערוך)", "100 גרם", "550", "7290000572673"));
        SystemProductArr.add(new Product(0, "עלי גפן ממולאים באורז, וילי פוד / Willi Food", "יחידה", "35", "7290003882922"));
        SystemProductArr.add(new Product(0, "עלי גפן ממולאים באורז, וילי פוד / Willi Food", "יחידה", "35", "7290003882922"));
        SystemProductArr.add(new Product(0, "עלי גפן ממולאים באורז, וילי פוד / Willi Food", "100 גרם", "135", "7290003882922"));
        SystemProductArr.add(new Product(0, "עלי גפן ממולאים באורז, וילי פוד / Willi Food", "100 גרם", "135", "7290003882922"));
        SystemProductArr.add(new Product(0, "כוס קפה", "כוס", "220", ""));
        SystemProductArr.add(new Product(0, "פריכיות שוקולד", "יחידה", "19", ""));
        SystemProductArr.add(new Product(0, "פריכיות שוקולד", "100 גרם", "462", ""));
        SystemProductArr.add(new Product(0, "כרוב ממולא בשר", "יחידה", "60", ""));
        SystemProductArr.add(new Product(0, "נאצוס, HotPop", "שקית (322)", "1558", ""));
        SystemProductArr.add(new Product(0, "נאצוס, HotPop", "100 גרם", "484", ""));
        SystemProductArr.add(new Product(0, "פרכיות שוקולד", "שקית (80)", "369", ""));
        SystemProductArr.add(new Product(0, "טופיפי", "יחידה", "43", ""));
        SystemProductArr.add(new Product(0, "דונאט ללא גלוטן", "100 גרם", "457", ""));
        SystemProductArr.add(new Product(0, "מגנום וניל שקדים , מגנום", "יחידה", "196", ""));
        SystemProductArr.add(new Product(0, "מגנום וניל שקדים , מגנום", "100 גרם", "334", ""));
        SystemProductArr.add(new Product(0, "נודלס מוגו", "מנה", "600", ""));
        SystemProductArr.add(new Product(0, "ציפס כחול", "100 גרם", "532", ""));
        SystemProductArr.add(new Product(0, "גלובצי", "מנה", "420", ""));
        SystemProductArr.add(new Product(0, "גלובצי", "100 גרם", "84", ""));
        SystemProductArr.add(new Product(0, "גלידה כוכב / גלידה פצפוצים כוכב , שטראוס", "יחידה", "220", ""));
        SystemProductArr.add(new Product(0, "גלידה כוכב / גלידה פצפוצים כוכב , שטראוס", "100 גרם", "244", ""));
        SystemProductArr.add(new Product(0, "נקניקיות עוף , זוגלובג", "יחידה", "57", ""));
        SystemProductArr.add(new Product(0, "נקניקיות עוף , זוגלובג", "100 גרם", "200", ""));
        SystemProductArr.add(new Product(0, "נקניקיות מיני", "יחידה", "30", ""));
        SystemProductArr.add(new Product(0, "נקניקיות מיני", "100 גרם", "252", ""));
        SystemProductArr.add(new Product(0, "חזה עוף", "מנה", "180", ""));
        SystemProductArr.add(new Product(0, "ציפס אפוי", "חופן", "60", ""));
        SystemProductArr.add(new Product(0, "ציפס אפוי", "100 גרם", "150", ""));
        SystemProductArr.add(new Product(0, "ציפס בטטה אפוי", "100 גרם", "130", ""));
        SystemProductArr.add(new Product(0, "תפוציפס גריל, עלית", "שקית (50)", "268", ""));
        SystemProductArr.add(new Product(0, "תפוציפס גריל, עלית", "שקית (200)", "1074", ""));
        SystemProductArr.add(new Product(0, "תפוציפס גריל, עלית", "100 גרם", "537", ""));
        SystemProductArr.add(new Product(0, "פריכיות דבש, אסם", "יחידה", "8", ""));
        SystemProductArr.add(new Product(0, "פריכיות דבש, אסם", "שקית (80)", "293", ""));
        SystemProductArr.add(new Product(0, "פריכיות דבש, אסם", "100 גרם", "366", ""));
        SystemProductArr.add(new Product(0, "לחמניה ללא גלוטן / לחמניית סנדוויץ ללא גלוטן", "יחידה", "370", ""));
        SystemProductArr.add(new Product(0, "לחמניה ללא גלוטן / לחמניית סנדוויץ ללא גלוטן", "100 גרם", "325", ""));
        SystemProductArr.add(new Product(0, "לחמניית המבורגר ללא גלוטן", "יחידה", "195", ""));
        SystemProductArr.add(new Product(0, "לחמניית המבורגר ללא גלוטן", "100 גרם", "218", ""));
        SystemProductArr.add(new Product(0, "כיסונים מוצרלה", "100 גרם", "280", ""));
        SystemProductArr.add(new Product(0, "גלידה סולרו מיני וניל תות שדה, שטראוס", "יחידה", "82", ""));
        SystemProductArr.add(new Product(0, "גלידה סולרו מיני וניל תות שדה, שטראוס", "100 גרם", "140", ""));
        SystemProductArr.add(new Product(0, "חזה עוף מבושל/צלוי", "יחידה", "210", ""));
        SystemProductArr.add(new Product(0, "חזה עוף מבושל מטוגן", "יחידה", "250", ""));
        SystemProductArr.add(new Product(0, "כיף כף, עלית", "יחידה", "58", ""));
        SystemProductArr.add(new Product(0, "כיף כף, עלית", "100 גרם", "510", ""));
        SystemProductArr.add(new Product(0, "פסק זמן,עלית", "יחידה קטנה (20 ג')", "110", ""));
        SystemProductArr.add(new Product(0, "פסק זמן,עלית", "יחידה (45 ג')", "248", ""));
        SystemProductArr.add(new Product(0, "פסק זמן,עלית", "100 גרם", "551", ""));
        SystemProductArr.add(new Product(0, "חטיף חלבון Go בטעם שוקולד, תנובה", "יחידה", "220", ""));
        SystemProductArr.add(new Product(0, "חטיף חלבון Go בטעם שוקולד, תנובה", "100 גרם", "366", ""));
        SystemProductArr.add(new Product(0, "לחמית אגוזים, אסם", "יחידה", "49", ""));
        SystemProductArr.add(new Product(0, "לחמית אגוזים, אסם", "אריזת ניילון", "691", ""));
        SystemProductArr.add(new Product(0, "לחמית אגוזים, אסם", "100 גרם", "432", ""));
        SystemProductArr.add(new Product(0, "היפופוטם קינדר / Happy Hippo , קינדר / Kinder", "יחידה", "123", "80176732 , 8000500023624"));
        SystemProductArr.add(new Product(0, "היפופוטם קינדר / Happy Hippo , קינדר / Kinder", "100 גרם", "593", "8000500023624"));
        SystemProductArr.add(new Product(0, "Happy Swing rolls - nut , Flis", "יחידה", "53", "5908234805666"));
        SystemProductArr.add(new Product(0, "Happy Swing rolls - nut , Flis", "100 גרם", "526", "5908234805666"));
        SystemProductArr.add(new Product(0, "נחשי גומי / תולעי גומי", "יחידה", "34", ""));
        SystemProductArr.add(new Product(0, "נחשי גומי / תולעי גומי", "100 גרם", "337", ""));
        SystemProductArr.add(new Product(0, "לקט ירקות לתנור , פרי הגליל", "100 גרם", "51", "7290017297194"));
        SystemProductArr.add(new Product(0, "פיצה", "משולש", "350", ""));
        SystemProductArr.add(new Product(0, "פיצה", "100 גרם", "266", ""));
        SystemProductArr.add(new Product(0, "תפוח אדמה אפוי קוביות של אמא", "יחידה", "10", ""));
        SystemProductArr.add(new Product(0, "ארטיקגרניטה אייס ונילה , גרניטה / Granita", "יחידה", "116", "7290101112464"));
        SystemProductArr.add(new Product(0, "ארטיקגרניטה אייס ונילה , גרניטה / Granita", "100 גרם", "145", "7290101112464"));
        SystemProductArr.add(new Product(0, "ארטיק מסטיק,  שלגוגו", "100 גרם", "80", "7290001426043"));
        SystemProductArr.add(new Product(0, "ארטיק מסטיק, שלגוגו", "יחידה", "56", "7290001426043"));
        SystemProductArr.add(new Product(0, "סוכריות חומוס, בני ריאד מחרום", "יחידה", "7", ""));
        SystemProductArr.add(new Product(0, "סוכריות חומוס, בני ריאד מחרום", "100 גרם", "395", "7290011239404"));
        SystemProductArr.add(new Product(0, "יוגורט קרמי בטעם תות, דנונה", "גביע", "130", "7290119375332"));
        SystemProductArr.add(new Product(0, "יוגורט קרמי בטעם תות, דנונה", "100 גרם", "87", "7290119375332"));
        SystemProductArr.add(new Product(0, "גלידה תות שמנת , בן אנד ג'ריס / Ben & Jerry", "קופסה (420)", "840", "076840620029"));
        SystemProductArr.add(new Product(0, "גלידה תות שמנת , בן אנד ג'ריס / Ben & Jerry", "כפית", "10", "076840620029"));
        SystemProductArr.add(new Product(0, "גלידה תות שמנת , בן אנד ג'ריס / Ben & Jerry", "100 גרם", "198", "076840620029"));
        SystemProductArr.add(new Product(0, "טובלרון", "משולש", "53", ""));
        SystemProductArr.add(new Product(0, "טובלרון", "משולש", "100", ""));
        SystemProductArr.add(new Product(0, "טובלרון", "יחידה קטנה", "53", ""));
        SystemProductArr.add(new Product(0, "טובלרון", "100 גרם", "529", "7614500035788"));
        SystemProductArr.add(new Product(0, "מילקה פרה / Choco Moo - ביסקוויט מצופה שוקולד חלב - מילקה שוקו מו , מילקה / milka", "יחידה", "65", "7622300864057"));
        SystemProductArr.add(new Product(0, "מילקה פרה / Choco Moo - ביסקוויט מצופה שוקולד חלב - מילקה שוקו מו , מילקה / milka", "100 גרם", "494", "7622300864057"));
        SystemProductArr.add(new Product(0, "אורז ועדשים עם טונה- עץ הזית", "יחידה (160)", "304", "7290017142418"));
        SystemProductArr.add(new Product(0, "אורז ועדשים עם טונה- עץ הזית", "100 גרם", "190", "7290017142418"));
        SystemProductArr.add(new Product(0, "פריכיות אורז מלא", "יחידה", "30", ""));
        SystemProductArr.add(new Product(0, "פריכיות אורז מלא", "100 גרם", "360", ""));
        SystemProductArr.add(new Product(0, "מקושקשת", "ביצה אחת", "75", ""));
        SystemProductArr.add(new Product(0, "מקושקשת", "100 גרם", "170", ""));
        SystemProductArr.add(new Product(0, "במבה במילוי קרם בטעם בראוניז, אסם", "יחידה", "6", "7290115209358"));
        SystemProductArr.add(new Product(0, "במבה במילוי קרם בטעם בראוניז, אסם", "שקית (60 ג')", "320", "7290115209358"));
        SystemProductArr.add(new Product(0, "במבה במילוי קרם בטעם בראוניז, אסם", "100 גרם", "534", "7290115209358"));
        SystemProductArr.add(new Product(0, "חזה עוף מוקפץ", "100 גרם", "85", ""));
        SystemProductArr.add(new Product(0, "נודלס עוף בקר מוקפץ מסעדה", "מנה", "900", ""));
        SystemProductArr.add(new Product(0, "גבינה צהובה מגורדת פתיתים 28%, אסם תנובה", "100 גרם", "345", ""));
        SystemProductArr.add(new Product(0, "גלילי ופל במילון קרם בטעם שוקולד, עלמה", "יחידה", "38", "7290011249748"));
        SystemProductArr.add(new Product(0, "גלילי ופל במילון קרם בטעם שוקולד, עלמה", "100 גרם", "475", "7290011249748"));
        SystemProductArr.add(new Product(0, "אחר / הוספת עצמית", "קלוריות", "1", ""));


        //ירקות פירות
        if (0 == 0) {
            SystemProductArr.add(new Product(0, "אגס", "יחידה קטנה", "95", ""));
            SystemProductArr.add(new Product(0, "אגס", "יחידה בינונית", "107", ""));
            SystemProductArr.add(new Product(0, "אגס", "יחידה גדולה", "135", ""));
            SystemProductArr.add(new Product(0, "אגס", "100 גרם", "58", ""));
            SystemProductArr.add(new Product(0, "גרגירי חומוס", "100 גרם", "120", ""));
            SystemProductArr.add(new Product(0, "זיתים", "יחידה", "5", ""));
            SystemProductArr.add(new Product(0, "זיתים", "100 גרם", "190", ""));
            SystemProductArr.add(new Product(0, "שן שום", "יחידה", "10", ""));
            SystemProductArr.add(new Product(0, "ראש שום", "יחידה", "110", ""));
            SystemProductArr.add(new Product(0, "מיץ לימון טבעי", "100 גרם", "22", ""));
            SystemProductArr.add(new Product(0, "לימון", "100 גרם", "29", ""));
            SystemProductArr.add(new Product(0, "תירס", "100 גרם", "108", ""));
            SystemProductArr.add(new Product(0, "קלח תירס", "יחידה", "200", ""));
            SystemProductArr.add(new Product(0, "בטטה מבושלת", "100 גרם", "76", ""));
            SystemProductArr.add(new Product(0, "בטטה אפוייה", "100 גרם", "90", ""));
            SystemProductArr.add(new Product(0, "ערמונים", "יחידה", "9", ""));
            SystemProductArr.add(new Product(0, "ערמונים", "100 גרם", "184", ""));
            SystemProductArr.add(new Product(0, "פטריה", "יחידה", "5", ""));
            SystemProductArr.add(new Product(0, "פטריות", "100 גרם", "22", ""));
            SystemProductArr.add(new Product(0, "קולורבי", "100 גרם", "27", ""));
            SystemProductArr.add(new Product(0, "שזיף", "יחידה", "62", ""));
            SystemProductArr.add(new Product(0, "שזיף", "100 גרם", "46", ""));
            SystemProductArr.add(new Product(0, "מלפפון", "יחידה", "12", ""));
            SystemProductArr.add(new Product(0, "מלפפון", "100 גרם", "12", ""));
            SystemProductArr.add(new Product(0, "מלפפון ללא קליפה", "יחידה", "9", ""));
            SystemProductArr.add(new Product(0, "מלפפון חמוץ", "יחידה קטנה", "1", ""));
            SystemProductArr.add(new Product(0, "מלפפון חמוץ", "יחידה גדולה", "5", ""));
            SystemProductArr.add(new Product(0, "מלפפון חמוץ במלח", "100 גרם", "10", ""));
            SystemProductArr.add(new Product(0, "תפוז", "יחידה", "50", ""));
            SystemProductArr.add(new Product(0, "ארטישוק מבושל", "100 גרם", "38", ""));
            SystemProductArr.add(new Product(0, "תחתיות ארטישוק", "100 גרם", "17", ""));
            SystemProductArr.add(new Product(0, "בצל יבש", "100 גרם", "42", ""));
            SystemProductArr.add(new Product(0, "גזר", "100 גרם", "34", ""));
            SystemProductArr.add(new Product(0, "גזר מבושל", "100 גרם", "30", ""));
            SystemProductArr.add(new Product(0, "דלעת מבושלת", "100 גרם", "21", ""));
            SystemProductArr.add(new Product(0, "חסה", "100 גרם", "13", ""));
            SystemProductArr.add(new Product(0, "חציל אפוי מבושל", "פרוסה", "5", ""));
            SystemProductArr.add(new Product(0, "חציל אפוי מבושל", "100 גרם", "17", ""));
            SystemProductArr.add(new Product(0, "חציל בינוני", "יחידה", "142", ""));
            SystemProductArr.add(new Product(0, "חציל", "100 גרם", "24", ""));
            SystemProductArr.add(new Product(0, "כרוב מבושל", "100 גרם", "17", ""));
            SystemProductArr.add(new Product(0, "כרובית מבושלת", "100 גרם", "20", ""));
            SystemProductArr.add(new Product(0, "פלפל ירוק", "100 גרם", "19", ""));
            SystemProductArr.add(new Product(0, "קישוא מבושל", "100 גרם", "12", ""));
            SystemProductArr.add(new Product(0, "שעועית ירוקה מבושלת", "100 גרם", "20", ""));
            SystemProductArr.add(new Product(0, "תירס מבושל", "100 גרם", "107", ""));
            SystemProductArr.add(new Product(0, "תרד מבושל", "100 גרם", "23", ""));
            SystemProductArr.add(new Product(0, "ענבים", "יחידה", "4", ""));
            SystemProductArr.add(new Product(0, "ענבים", "100 גרם", "67", ""));
            SystemProductArr.add(new Product(0, "תות קטן", "יחידה", "3", ""));
            SystemProductArr.add(new Product(0, "תות בינוני", "יחידה", "6", ""));
            SystemProductArr.add(new Product(0, "תות גדול", "יחידה", "10", ""));
            SystemProductArr.add(new Product(0, "תות", "100 גרם", "32", ""));
            SystemProductArr.add(new Product(0, "אבוקדו קטן", "יחידה", "230", ""));
            SystemProductArr.add(new Product(0, "אבוקדו בינוני", "יחידה", "280", ""));
            SystemProductArr.add(new Product(0, "אבוקדו גדול", "יחידה", "320", ""));
            SystemProductArr.add(new Product(0, "אבוקדו", "100 גרם", "160", ""));
            SystemProductArr.add(new Product(0, "נקטרינה קטנה", "יחידה", "60", ""));
            SystemProductArr.add(new Product(0, "נקטרינה בינונית", "יחידה", "75", ""));
            SystemProductArr.add(new Product(0, "נקטרינה גדולה", "יחידה", "90", ""));
            SystemProductArr.add(new Product(0, "משמש", "יחידה", "18", ""));
            SystemProductArr.add(new Product(0, "משמש", "100 גרם", "48", ""));
            SystemProductArr.add(new Product(0, "אפרסק בינוני", "יחידה", "60", ""));
            SystemProductArr.add(new Product(0, "אפרסק קטן", "יחידה", "50", ""));
            SystemProductArr.add(new Product(0, "אפרסק גדול", "יחידה", "80", ""));
            SystemProductArr.add(new Product(0, "אפרסק", "100 גרם", "39", ""));
            SystemProductArr.add(new Product(0, "דובדבן", "יחידה", "6", ""));
            SystemProductArr.add(new Product(0, "דובדבנים", "100 גרם", "60", ""));
            SystemProductArr.add(new Product(0, "דובדבן חמוץ", "יחידה", "5", ""));
            SystemProductArr.add(new Product(0, "דובדבן חמוץ", "100 גרם", "50", ""));
            SystemProductArr.add(new Product(0, "פסיפלורה", "יחידה", "20", ""));
            SystemProductArr.add(new Product(0, "אננס", "פרוסה", "30", ""));
            SystemProductArr.add(new Product(0, "אגוז מלך", "יחידה", "30", ""));
            SystemProductArr.add(new Product(0, "אגוז מלך", "100 גרם", "655", ""));
            SystemProductArr.add(new Product(0, "אגוז ברזילאי", "יחידה", "30", ""));
            SystemProductArr.add(new Product(0, "אגוז ברזילאי", "100 גרם", "655", ""));
            SystemProductArr.add(new Product(0, "אגוז פקאן", "יחידה", "20", ""));
            SystemProductArr.add(new Product(0, "אגוז פקאן", "100 גרם", "690", ""));
            SystemProductArr.add(new Product(0, "אגוז מקדמיה", "יחידה", "25", ""));
            SystemProductArr.add(new Product(0, "אגוז מקדמיה", "100 גרם", "718", ""));
            SystemProductArr.add(new Product(0, "אגוז לוז", "יחידה", "12", ""));
            SystemProductArr.add(new Product(0, "אגוז לוז", "100 גרם", "630", ""));
            SystemProductArr.add(new Product(0, "קשיו", "יחידה", "9", ""));
            SystemProductArr.add(new Product(0, "קשיו", "100 גרם", "550", ""));
            SystemProductArr.add(new Product(0, "שקד", "יחידה", "6", ""));
            SystemProductArr.add(new Product(0, "שקד", "100 גרם", "575", ""));
            SystemProductArr.add(new Product(0, "בוטנים", "יחידה", "9", ""));
            SystemProductArr.add(new Product(0, "בוטנים", "100 גרם", "585", ""));
            SystemProductArr.add(new Product(0, "סלק", "יחידה", "55", ""));
            SystemProductArr.add(new Product(0, "סלק", "100 גרם", "43", ""));
            SystemProductArr.add(new Product(0, "בננה", "יחידה", "100", ""));
            SystemProductArr.add(new Product(0, "תמר מגהול", "יחידה", "45", ""));
            SystemProductArr.add(new Product(0, "תמר מגהול", "100 גרם", "277", ""));
            SystemProductArr.add(new Product(0, "צנון", "יחידה קטנה", "1", ""));
            SystemProductArr.add(new Product(0, "צנון", "יחידה גדולה", "7", ""));
            SystemProductArr.add(new Product(0, "צנון", "100 גרם", "16", ""));
            SystemProductArr.add(new Product(0, "תפוח (180 גרם)", "יחידה", "95", ""));
            SystemProductArr.add(new Product(0, "תפוח", "100 גרם", "52", ""));
            SystemProductArr.add(new Product(0, "עגבנייה", "יחידה", "30", ""));
            SystemProductArr.add(new Product(0, "עגבניה", "100 גרם", "18", ""));
            SystemProductArr.add(new Product(0, "רסק עגבניות", "100 גרם", "72", ""));
            SystemProductArr.add(new Product(0, "אבטיח קוביות", "כוס", "45", ""));
            SystemProductArr.add(new Product(0, "אבטיח", "100 גרם", "31", ""));
            SystemProductArr.add(new Product(0, "אדממה מבושלת", "100 גרם", "122", ""));
            SystemProductArr.add(new Product(0, "שום", "100 גרם", "150", ""));
            SystemProductArr.add(new Product(0, "פלפל חריף", "100 גרם", "40", ""));
            SystemProductArr.add(new Product(0, "מנגו", "100 גרם", "60", ""));
            SystemProductArr.add(new Product(0, "תרד", "100 גרם", "23", ""));
            SystemProductArr.add(new Product(0, "בצל קטן", "יחידה", "25", ""));
            SystemProductArr.add(new Product(0, "בצל בינוני", "יחידה", "50", ""));
            SystemProductArr.add(new Product(0, "בצל גדול", "יחידה", "125", ""));
            SystemProductArr.add(new Product(0, "בצל", "100 גרם", "40", ""));
            SystemProductArr.add(new Product(0, "אפונה מבושלת", "100 גרם", "85", ""));
            SystemProductArr.add(new Product(0, "תפוח אדמה", "פרוסה", "40", ""));
            SystemProductArr.add(new Product(0, "תפוח אדמה", "100 גרם", "86", ""));
            SystemProductArr.add(new Product(0, "תפוח אדמה קטן", "יחידה", "70", ""));
            SystemProductArr.add(new Product(0, "תפוח אדמה בינוני", "יחידה", "120", ""));
            SystemProductArr.add(new Product(0, "תפוח אדמה גדול", "יחידה", "240", ""));

        }
        //מהחיי
        if (0 == 0) {

            SystemProductArr.add(new Product(0, "נקניק קבנוס, זוגלובק", "יחידה", "147", "7290012226120"));
            SystemProductArr.add(new Product(0, "נקניק קבנוס, זוגלובק", "100 גרם", "325", "7290012226120"));
            SystemProductArr.add(new Product(0, "שוק עוף", "יחידה", "150", ""));
            SystemProductArr.add(new Product(0, "שוק עוף", "100 גרם", "185", ""));
            SystemProductArr.add(new Product(0, "כרע עוף מבושל", "יחידה", "405", ""));
            SystemProductArr.add(new Product(0, "כרע עוף מבושל", "100 גרם", "172", ""));
            SystemProductArr.add(new Product(0, "פרגית עוף בתנור", "יחידה", "230", ""));
            SystemProductArr.add(new Product(0, "פרגית עוף", "100 גרם", "190", ""));
            SystemProductArr.add(new Product(0, "טונה בשמן, פרי הגלי", "100 גרם", "133", ""));
            SystemProductArr.add(new Product(0, "יוגורט טבעי", "100 גרם", "58", ""));
            SystemProductArr.add(new Product(0, "בשר בקר טחון מטוגן", "100 גרם", "240", ""));
            SystemProductArr.add(new Product(0, "ביצה", "יחידה", "60", ""));
            SystemProductArr.add(new Product(0, "חלמון ביצה", "יחידה", "58", ""));
            SystemProductArr.add(new Product(0, "טונה בשמן", "כף", "40", ""));
            SystemProductArr.add(new Product(0, "טונה בשמן", "כפית", "25", ""));
            SystemProductArr.add(new Product(0, "טונה בשמן", "100 גרם", "200", ""));
            SystemProductArr.add(new Product(0, "דג אמנון ", "100 גרם", "130", ""));
            SystemProductArr.add(new Product(0, "פסטרמה", "פרוסה", "20", ""));
            SystemProductArr.add(new Product(0, "חזה עוף מבושל", "100 גרם", "165", ""));
            SystemProductArr.add(new Product(0, "חזה עוף צלוי", "100 גרם", "165", ""));
            SystemProductArr.add(new Product(0, "חזה עוף מטוגן", "100 גרם", "185", ""));
            SystemProductArr.add(new Product(0, "שניצל מטוגן", "100 גרם", "220", ""));
            SystemProductArr.add(new Product(0, "גבינה צהובה 28%", "פרוסה", "97", ""));
            SystemProductArr.add(new Product(0, "גבינה צהובה 28%", "100 גרם", "345", ""));
            SystemProductArr.add(new Product(0, "בולגרית 5%", "100 גרם", "95", ""));
            SystemProductArr.add(new Product(0, "מוצרלה, תנובה", "פרוסה", "56", ""));
            SystemProductArr.add(new Product(0, "גבינת מוצרלה, תנובה", "100 גרם", "285", ""));
            SystemProductArr.add(new Product(0, "לבן אשל 4.5%", "יחידה", "140", "7290004125400"));
            SystemProductArr.add(new Product(0, "חלב 3%", "כוס", "150", ""));
            SystemProductArr.add(new Product(0, "חלב 3%", "100 מל", "60", ""));
            SystemProductArr.add(new Product(0, "מיני מו מטבעות גבינה 27%, מיני מווו", "יחידה", "64", "7290117263792"));
            SystemProductArr.add(new Product(0, "מיני מו מטבעות גבינה 27%, מיני מווו", "100 גרם", "319", "7290117263792"));

        }
        //פחמימות(1)
        if (0 == 0) {

            SystemProductArr.add(new Product(0, "דייסת שיבולת שועל בוקר", "יחידה", "250", ""));
            SystemProductArr.add(new Product(0, "קרקר", "יחידה", "25", ""));
            SystemProductArr.add(new Product(0, "קרקר", "100 גרם", "504", ""));
            SystemProductArr.add(new Product(0, "מקל שום", "יחידה", "120", ""));
            SystemProductArr.add(new Product(0, "מקל שום", "100 גרם", "260", ""));
            SystemProductArr.add(new Product(0, "לחם שום", "מקל", "120", ""));
            SystemProductArr.add(new Product(0, "לחם שום", "100 גרם", "260", ""));
            SystemProductArr.add(new Product(0, "קרוטונים", "חופן", "118", ""));
            SystemProductArr.add(new Product(0, "קרוטונים", "100 גרם", "407", ""));
            SystemProductArr.add(new Product(0, "כדור פלאפל", "יחידה", "70", ""));
            SystemProductArr.add(new Product(0, "כדור פלאפל", "100 גרם", "350", ""));
            SystemProductArr.add(new Product(0, "טופו", "קוביה קטנה", "10", ""));
            SystemProductArr.add(new Product(0, "טופו", "100 גרם", "150", ""));
            SystemProductArr.add(new Product(0, "בגט", "יחידה", "650", ""));
            SystemProductArr.add(new Product(0, "בגט", "100 גרם", "270", ""));
            SystemProductArr.add(new Product(0, "לחמניה", "יחידה", "200", ""));
            SystemProductArr.add(new Product(0, "לחמניה", "100 גרם", "270", ""));
            SystemProductArr.add(new Product(0, "פיתה", "יחידה", "240", ""));
            SystemProductArr.add(new Product(0, "פיתה", "100 גרם", "240", ""));
            SystemProductArr.add(new Product(0, "פיתה ביס", "יחידה", "120", ""));
            SystemProductArr.add(new Product(0, "אורז לבן מבושל", "כף", "30", ""));
            SystemProductArr.add(new Product(0, "אורז בסמטי מבושל", "100 גרם", "125", ""));
            SystemProductArr.add(new Product(0, "עלי גפן ממולאים באורז", "יחידה", "35", ""));
            SystemProductArr.add(new Product(0, "פתיתים מבושלים", "כף", "40", ""));
            SystemProductArr.add(new Product(0, "פתיתים מבושלים", "100 גרם", "190", ""));
            SystemProductArr.add(new Product(0, "קוסקוס", "כף", "25", ""));
            SystemProductArr.add(new Product(0, "קוסקוס", "100 גרם", "115", ""));
            SystemProductArr.add(new Product(0, "מגדרה", "100 גרם", "165", ""));
            SystemProductArr.add(new Product(0, "ספגטי", "100 גרם", "150", ""));
            SystemProductArr.add(new Product(0, "פסטה", "100 גרם", "150", ""));
            SystemProductArr.add(new Product(0, "פסטה מסולסלת מבושלת", "יחידה", "7", ""));
            SystemProductArr.add(new Product(0, "פסטה מסולסלת מבושלת", "100 גרם", "192", ""));
            SystemProductArr.add(new Product(0, "לחם", "פרוסה", "75", ""));
            SystemProductArr.add(new Product(0, "לחם", "100 גרם", "265", ""));
            SystemProductArr.add(new Product(0, "לחמנית פרנה", "יחידה מלבן", "390", ""));
            SystemProductArr.add(new Product(0, "לחמנית פרנה", "100 גרם", "245", ""));
            SystemProductArr.add(new Product(0, "לחם אחיד פרוס", "פרוסה", "75", ""));
            SystemProductArr.add(new Product(0, "לחם אחיד פרוס, אנג'ל", "100 גרם", "237", ""));
            SystemProductArr.add(new Product(0, "לחם מחמצת", "100 גרם", "290", ""));
            SystemProductArr.add(new Product(0, "לחמניות פרנה ביס, Frena", "יחידה", "110", ""));
            SystemProductArr.add(new Product(0, "לחמניות פרנה ביס, Frena", "100 גרם", "277", ""));
            SystemProductArr.add(new Product(0, "קמח תפוחי אדמה", "100 גרם", "357", ""));
            SystemProductArr.add(new Product(0, "צנים / לחם קלוי", "יחידה", "75", ""));
            SystemProductArr.add(new Product(0, "טורטייה קמח חיטה, מאסטר שף", "יחידה", "128", ""));
            SystemProductArr.add(new Product(0, "טורטייה קמח חיטה, מאסטר שף", "100 גרם", "320", ""));
            SystemProductArr.add(new Product(0, "טורטייה מקמח חיטה 25 סמ, שקדיה", "יחידה", "220", "7290008830690"));
            SystemProductArr.add(new Product(0, "טורטייה מקמח חיטה, שקדיה", "100 גרם", "314", "7290008830690"));
            SystemProductArr.add(new Product(0, "טורטייה בתוספת חיטה מלאה 20 סמ, שקדיה", "יחידה", "129", "7290008830690"));
            SystemProductArr.add(new Product(0, "טורטייה בתוספת חיטה מלאה 20 סמ, שקדיה", "100 גרם", "287", "7290008830690"));
            SystemProductArr.add(new Product(0, "סמבוסק גבינה", "יחידה", "350", ""));

        }
        //חטיפים ממתקים וכו
        if (0 == 0) {

            SystemProductArr.add(new Product(0, "מייק אנד אייק בטעם פירות", "יחידה", "7", "070970471254"));
            SystemProductArr.add(new Product(0, "מייק אנד אייק בטעם פירות", "100 גרם", "367", "070970471254"));
            SystemProductArr.add(new Product(0, "m&m אם אנד אמס חמאת בוטנים", "יחידה", "10", "040000513629"));
            SystemProductArr.add(new Product(0, "m&m אם אנד אמס חמאת בוטנים", "100 גרם", "516", "040000513629"));
            SystemProductArr.add(new Product(0, "עוגיות ריבה פרחים", "יחידה", "75", ""));
            SystemProductArr.add(new Product(0, "עוגיות ריבה פרחים", "100 גרם", "498", ""));
            SystemProductArr.add(new Product(0, "עוגיות סנדוויץ בטעם קרמל במילוי קרם קרמל, Lotus", "יחידה", "60", "5410126006360"));
            SystemProductArr.add(new Product(0, "עוגיות סנדוויץ בטעם קרמל במילוי קרם קרמל,Lotus ", "100 גרם", "522", "5410126006360"));
            SystemProductArr.add(new Product(0, "קינדר אצבעות שוקולד חלב, Kinder", "יחידה", "71", "8000500018828 , 80177616 , 80177609 ,8000500071083 , 80310167 , 40084077 "));
            SystemProductArr.add(new Product(0, "קינדר אצבעות שוקולד חלב, Kinder", "100 גרם", "566", "8000500018828 , 80177616 , 80177609 ,8000500071083 , 80310167 , 40084077 "));
            SystemProductArr.add(new Product(0, "מרמלדה", "100 גרם", "320", ""));
            SystemProductArr.add(new Product(0, "חטיף בוטנים , א.אטיאס", "100 גרם", "503", "7290000194172"));
            SystemProductArr.add(new Product(0, "חלביצה", "100 גרם", "480", ""));
            SystemProductArr.add(new Product(0, "חטיף אגוזים שקדים וניל, רפאלס", "יחידה", "140", "7290018333983"));
            SystemProductArr.add(new Product(0, "חטיף אגוזים שקדים וניל, רפאלס", "100 גרם", "466", "7290018333983"));
            SystemProductArr.add(new Product(0, "חטיפי קרקר מלוח, אסם", "יחידה", "11", "7290000069715"));
            SystemProductArr.add(new Product(0, "חטיפי קרקר מלוח, אסם", "100 גרם", "490", "7290000069715"));
            SystemProductArr.add(new Product(0, "ביסלי במבה מיקס", "100 גרם", "510", "7290106578692"));
            SystemProductArr.add(new Product(0, "מאפין, אחוה", "יחידה", "206", "7290006775191"));
            SystemProductArr.add(new Product(0, "מאפין, אחווה", "100 גרם", "415", "7290006775191"));
            SystemProductArr.add(new Product(0, "קראנץ שוקולד בלונד נוגט בוטנים", "100 גרם", "377", "7290018131640"));
            SystemProductArr.add(new Product(0, "קראנץ שוקולד לבן פיסטוק", "100 גרם", "401", "7290018652947"));
            SystemProductArr.add(new Product(0, "קרמבו", "יחידה", "105", ""));
            SystemProductArr.add(new Product(0, "קרמבו", "100 גרם", "420", ""));
            SystemProductArr.add(new Product(0, "שלוק", "יחידה גדולה", "60", ""));
            SystemProductArr.add(new Product(0, "שלוק", "יחידה קטנה", "15", ""));
            SystemProductArr.add(new Product(0, "שלוק", "100 גרם", "52", ""));
            SystemProductArr.add(new Product(0, "סוכרייה על מקל", "יחידה", "60", ""));
            SystemProductArr.add(new Product(0, "בייגלה שמניות מלח , בייגל בייגל", "יחידה", "5", "7290000461625"));
            SystemProductArr.add(new Product(0, "בייגלה שמניות מלח , בייגל בייגל", "100 גרם", "382", "7290000461625"));
            SystemProductArr.add(new Product(0, "נשנושים קרקר קוקטייל שומשום, בייגל בייגל", "יחידה", "5", ""));
            SystemProductArr.add(new Product(0, "נשנושים קרקר קוקטייל שומשום, בייגל בייגל", "100 גרם", "516", "7290112495174"));
            SystemProductArr.add(new Product(0, "נשנושים קרקר עיגולים מלוחים, בייגל בייגל", "יחידה", "8", ""));
            SystemProductArr.add(new Product(0, "נשנושים קרקר עיגולים מלוחים, בייגל בייגל", "100 גרם", "515", "7290112495150"));
            SystemProductArr.add(new Product(0, "נשנושים חטיף זעתר, בייגל בייגל", "יחידה", "5", ""));
            SystemProductArr.add(new Product(0, "נשנושים חטיף זעתר, בייגל בייגל", "100 גרם", "511", "7290112495112"));
            SystemProductArr.add(new Product(0, "ופלים מצופים, מן", "יחידה", "116", "7290000311029"));
            SystemProductArr.add(new Product(0, "ופלים מצופים, מן", "100 גרם", "520", "7290000311425"));
            SystemProductArr.add(new Product(0, "חטיף תמרים טבעי במילוי חמאת שקדים", "יחידה", "93", "7290016146745"));
            SystemProductArr.add(new Product(0, "חטיף תמרים טבעי במילוי חמאת שקדים", "100 גרם", "369", "7290016146745"));
            SystemProductArr.add(new Product(0, "שוקולד לבן", "קוביה", "23", ""));
            SystemProductArr.add(new Product(0, "שוקולד לבן", "100 גרם", "540", ""));
            SystemProductArr.add(new Product(0, "גריסיני, מאיר ביגל", "יחידה", "30", ""));
            SystemProductArr.add(new Product(0, "גריסיני, מאיר ביגל", "100 גרם", "411", "7290017928821"));
            SystemProductArr.add(new Product(0, "גריסיני שומשום, מאיר ביגל", "יחידה", "30", ""));
            SystemProductArr.add(new Product(0, "גריסיני שומשום, מאיר ביגל", "100 גרם", "411", "7290017928036"));
            SystemProductArr.add(new Product(0, "תפוציפס מלח ופלפל", "100 גרם", "537", "7290106662025"));
            SystemProductArr.add(new Product(0, "תפוציפס מלח וחומץ", "100 גרם", "535", "7290115676990"));
            SystemProductArr.add(new Product(0, "קוביות וופלים במילוי אגוזים", "יחידה", "26", ""));
            SystemProductArr.add(new Product(0, "קוביות וופלים במילוי אגוזים", "100 גרם", "520", "7296073226536"));
            SystemProductArr.add(new Product(0, "פרינגלס טבעי", "100 גרם", "531", "0038000232183"));
            SystemProductArr.add(new Product(0, "פרינגלס שמנת חמוצה ובצל", "100 גרם", "523", "038000232176,38000232176,38000845253,038000845253"));
            SystemProductArr.add(new Product(0, "פרינגלס ברביקיו", "יחידה", "11", ""));
            SystemProductArr.add(new Product(0, "פרינגלס ברביקיו", "100 גרם", "527", "038000232152,38000232152"));
            SystemProductArr.add(new Product(0, "פרינגלס פיצה", "100 גרם", "531", "38000138638"));
            SystemProductArr.add(new Product(0, "דובדבן מסוכר", "יחידה", "9", ""));
            SystemProductArr.add(new Product(0, "דובדבן מסוכר", "100 גרם", "273", ""));
            SystemProductArr.add(new Product(0, "מנטוס", "יחידה", "8", ""));
            SystemProductArr.add(new Product(0, "סוכריית סודה", "יחידה", "30", ""));
            SystemProductArr.add(new Product(0, "סוכריית סודה", "יחידה גדולה", "50", ""));
            SystemProductArr.add(new Product(0, "גלי תות מוכן", "100 גרם", "44", ""));
            SystemProductArr.add(new Product(0, "גלי תות אבקה", "100 גרם", "388", ""));
            SystemProductArr.add(new Product(0, "אוזן המן", "יחידה", "140", ""));
            SystemProductArr.add(new Product(0, "ציטוס puffs בטעם גבינה", "יחידה", "6", ""));
            SystemProductArr.add(new Product(0, "ציטוס puffs בטעם גבינה", "100 גרם", "537", ""));
            SystemProductArr.add(new Product(0, "דובשניות, חפץ", "יחידה", "20", ""));
            SystemProductArr.add(new Product(0, "דובשניות, חפץ", "100 גרם", "280", ""));
            SystemProductArr.add(new Product(0, "שוקולד בצורת צדפות, צוקטה", "יחידה", "75", ""));
            SystemProductArr.add(new Product(0, "שוקולד בצורת צדפות, צוקטה", "100 גרם", "561", ""));
            SystemProductArr.add(new Product(0, "פררו רושה, Ferrero", "יחידה", "73", ""));
            SystemProductArr.add(new Product(0, "פררו רושה, Ferrero", "100 גרם", "582", ""));
            SystemProductArr.add(new Product(0, "וופל במילוי קרם קוקוס patisserie, לואקר", "100 גרם", "568", ""));
            SystemProductArr.add(new Product(0, "תפוציפס טבעי", "100 גרם", "549", "7290010118328"));
            SystemProductArr.add(new Product(0, "באהבה סוכריית לב בטעם דובדבן, וקסמן", "יחידה", "60", ""));
            SystemProductArr.add(new Product(0, "באהבה סוכריית לב בטעם דובדבן, וקסמן", "100 גרם", "395", ""));
            SystemProductArr.add(new Product(0, "ציפס מטוגן", "100 גרם", "320", ""));
            SystemProductArr.add(new Product(0, "עוגיות איטלקיות מובחרות", "יחידה", "36", ""));
            SystemProductArr.add(new Product(0, "עוגיות איטלקיות מובחרות", "100 גרם", "451", ""));
            SystemProductArr.add(new Product(0, "מיני קוקוס עוגיות בטעם חמאה, כרמית", "יחידה", "25", ""));
            SystemProductArr.add(new Product(0, "מיני קוקוס עוגיות בטעם חמאה, כרמית", "100 גרם", "515", "7290010329854"));
            SystemProductArr.add(new Product(0, "בייגלה שמיניות שומשום", "יחידה", "6", ""));
            SystemProductArr.add(new Product(0, "בייגלה שמיניות שומשום", "100 גרם", "359", ""));
            SystemProductArr.add(new Product(0, "פרכיות אורז", "יחידה", "30", ""));
            SystemProductArr.add(new Product(0, "ערגליות שוקו", "יחידה", "48", ""));
            SystemProductArr.add(new Product(0, "ערגליות שוקו", "100 גרם", "421", ""));
            SystemProductArr.add(new Product(0, "ערגליות תות", "יחידה", "45", ""));
            SystemProductArr.add(new Product(0, "ערגליות תות, אסם", "100 גרם", "415", ""));
            SystemProductArr.add(new Product(0, "אוראו", "יחידה", "53", ""));
            SystemProductArr.add(new Product(0, "אוראו", "100 גרם", "480", ""));
            SystemProductArr.add(new Product(0, "שוקולד חלב", "קוביה", "22", ""));
            SystemProductArr.add(new Product(0, "שוקולד חלב", "100 גרם", "530", ""));
            SystemProductArr.add(new Product(0, "שוקולד מריר", "קוביה", "25", ""));
            SystemProductArr.add(new Product(0, "שוקולד מריר", "100 גרם", "550", ""));
            SystemProductArr.add(new Product(0, "שוקולד חלב מילקה, milka", "קוביה", "22", ""));
            SystemProductArr.add(new Product(0, "שוקולד חלב מילקה, milka", "שורה", "88", ""));
            SystemProductArr.add(new Product(0, "שוקולד חלב מילקה, milka", "100 גרם", "530", ""));
            SystemProductArr.add(new Product(0, "שוקולד בלונדי, עלית", "קוביה", "30", "7290112351807"));
            SystemProductArr.add(new Product(0, "שוקולד בלונדי, עלית", "100 גרם", "551", "7290112351807"));
            SystemProductArr.add(new Product(0, "הרשיז דרופס,Hershey's", "יחידה", "15", ""));
            SystemProductArr.add(new Product(0, "הרשיז דרופס,Hershey's", "100 גרם", "521", "034000996643"));
            SystemProductArr.add(new Product(0, "קינדר קארדס, kinder", "יחידה", "65", "80874652"));
            SystemProductArr.add(new Product(0, "קינדר קארדס, kinder", "מארז 2×", "123", "80874652"));
            SystemProductArr.add(new Product(0, "קינדר קארדס, kinder", "100 גרם", "516", "8000500269169"));
            SystemProductArr.add(new Product(0, "רבע לשבע טורטית, עלית", "יחידה", "50", "7290112331946"));
            SystemProductArr.add(new Product(0, "רבע לשבע טורטית, עלית", "100 גרם", "502", "7290112331946"));
            SystemProductArr.add(new Product(0, "מילקה שוקו מו, milka", "יחידה", "66", "7622300503079"));
            SystemProductArr.add(new Product(0, "מילקה שוקו מו, milka", "100 גרם", "494", "7622300503079"));
            SystemProductArr.add(new Product(0, "ריזיס טבלה בטעם שוקולד חלב ריסס במילוי חמאת בוטנים, reese's", "קוביה", "54", "34000442652 , 034000442652"));
            SystemProductArr.add(new Product(0, "ריזיס טבלה בטעם שוקולד חלב ריסס במילוי חמאת בוטנים, reese's", "100 גרם", "540", "34000442652 , 034000442652"));
            SystemProductArr.add(new Product(0, "ריזיס עגול ריסס שוקולד חלב במילוי חמאת בוטנים, reese's", "100 גרם", "509", "3444009"));
            SystemProductArr.add(new Product(0, "ריזיס עגול ריסס שוקולד לבן במילוי חמאת בוטנים, reese's", "100 גרם", "536", "3402809"));
            SystemProductArr.add(new Product(0, "קיטקט מיני kitkat chunky mini , nestle", "יחידה", "84", "7613036710879"));
            SystemProductArr.add(new Product(0, "קיטקט מיני kitkat chunky mini , nestle", "100 גרם", "516", "7613036710879"));
            SystemProductArr.add(new Product(0, "חטיף עב דגנים עם שקדים ושוקולד מריר, שקדיה", "יחידה", "73", "107374190"));
            SystemProductArr.add(new Product(0, "חטיף עב דגנים עם שקדים ושוקולד מריר, שקדיה", "100 גרם", "418", ""));
            SystemProductArr.add(new Product(0, "חטיף גרנולה בתוספת אגוזים ושקדים, שקדיה", "יחידה", "81", "6009684860973"));
            SystemProductArr.add(new Product(0, "חטיף גרנולה בתוספת אגוזים ושקדים, שקדיה", "100 גרם", "463", "6009684860973"));
            SystemProductArr.add(new Product(0, "פיטנס חטיף אנרגייה קרם עוגיות פיטנס- חטיף דגני בוקר עם עוגיות ונטיפי שוקולד לבן, פיטנס", "יחידה", "93", "5900020018892"));
            SystemProductArr.add(new Product(0, "פיטנס חטיף אנרגייה קרם עוגיות פיטנס- חטיף דגני בוקר עם עוגיות ונטיפי שוקולד לבן, פיטנס", "100 גרם", "396", "5900020018908"));
            SystemProductArr.add(new Product(0, "נייצר ואלי שיבולת שועל עם קינמון, Nature valley", "יחידה", "191", "016000548602 , 016000548695"));
            SystemProductArr.add(new Product(0, "נייצר ואלי שיבולת שועל עם קינמון, Nature valley", "100 גרם", "454", ""));
            SystemProductArr.add(new Product(0, "נייצר ואלי שיבולת שועל עם דבש, Nature valley", "יחידה", "98", "016000548497,16000548404"));
            SystemProductArr.add(new Product(0, "נייצר ואלי שיבולת שועל עם דבש, Nature valley", "100 גרם", "467", "016000548497,16000548404"));
            SystemProductArr.add(new Product(0, "נייצר ואלי שיבולת שועל עם מייפל קנדי, Nature valley", "יחידה", "98", ""));
            SystemProductArr.add(new Product(0, "נייצר ואלי שיבולת שועל עם מייפל קנדי, Nature valley", "100 גרם", "465", ""));
            SystemProductArr.add(new Product(0, "נייצר ואלי שיבולת שועל עם שבבי שוקולד מריר, Nature valley", "יחידה", "99", "16000423534,016000507777"));
            SystemProductArr.add(new Product(0, "נייצר ואלי שיבולת שועל עם שבבי שוקולד מריר, Nature valley", "100 גרם", "473", "016000507777,16000423534"));
            SystemProductArr.add(new Product(0, "חטיף דגנים בטעם אגוזים, Fitness", "יחידה", "87", ""));
            SystemProductArr.add(new Product(0, "חטיף דגנים בטעם אגוזים, Fitness", "100 גרם", "386", ""));
            SystemProductArr.add(new Product(0, "חטיף דגנים שוקולד לבן, Fitness", "יחידה", "86", ""));
            SystemProductArr.add(new Product(0, "חטיף דגנים קרם עוגיות, Fitness", "יחידה", "94", ""));
            SystemProductArr.add(new Product(0, "קורני חטיף דגנים עם שוקולד חלב, corny", "יחידה", "114", "4011800628512"));
            SystemProductArr.add(new Product(0, "קורני חטיף דגנים עם שוקולד חלב, corny", "100 גרם", "456", "4011800628512"));
            SystemProductArr.add(new Product(0, "süb&salzig corny קורני בוטנים", "יחידה", "123", "4011800571726"));
            SystemProductArr.add(new Product(0, " süb&salzig corny קורני בוטנים", "100 גרם", "491", "4011800571726 , 4011800528416"));
            SystemProductArr.add(new Product(0, "שוגי (אדום) פתיתי תירס קלויים, תלמה", "יחידה", "124", "72992906"));
            SystemProductArr.add(new Product(0, "שוגי (אדום) פתיתי תירס קלויים, תלמה", "100 גרם", "479", "7290107646147"));
            SystemProductArr.add(new Product(0, "כדור שוקולד", "יחידה", "90", ""));
            SystemProductArr.add(new Product(0, "פופקורן", "חופן", "12", ""));
            SystemProductArr.add(new Product(0, "פופקורן", "כוס", "35", ""));
            SystemProductArr.add(new Product(0, "פופקורן", "100 גרם", "380", ""));
            SystemProductArr.add(new Product(0, "פופקורן בטעם חמאה", "חופן", "15", ""));
            SystemProductArr.add(new Product(0, "פופקורן בטעם חמאה", "כוס", "50", ""));
            SystemProductArr.add(new Product(0, "פופקורן בטעם חמאה", "100 גרם", "500", ""));
            SystemProductArr.add(new Product(0, "חמצוצים עגולים יוגוטה", "יחידה", "45", ""));
            SystemProductArr.add(new Product(0, "גלידה אמריקאית", "100 גרם", "222", ""));
            SystemProductArr.add(new Product(0, "גלידה אמריקאית בגביע, מקדונלדס", "יחידה", "154", ""));
            SystemProductArr.add(new Product(0, "גלידה אמריקאית, דלי קרים", "יחידה", "170", ""));
            SystemProductArr.add(new Product(0, "גביע גלידה", "יחידה", "25", ""));
            SystemProductArr.add(new Product(0, "וופל שוקולד, מן", "יחידה", "25", ""));
            SystemProductArr.add(new Product(0, "וופל קפה, מן", "יחידה", "51", ""));
            SystemProductArr.add(new Product(0, "חלבה בטעם וניל, אחווה", "100 גרם", "550", ""));
            SystemProductArr.add(new Product(0, "חלבה בטעם שוקו וניל, אחווה", "100 גרם", "567", ""));
            SystemProductArr.add(new Product(0, "עוגיות שטרודל עם מילוי תפוחים, Merba", "יחידה", "97", ""));
            SystemProductArr.add(new Product(0, "עוגיות שטרודל עם מילוי תפוחים, Merba", "100 גרם", "484", ""));
            SystemProductArr.add(new Product(0, "עוגיות שוקולד ציפס עם פירות יער, Merba", "יחידה ", "105", ""));
            SystemProductArr.add(new Product(0, "עוגיות שוקולד ציפס עם פירות יער, Merba", "100 גרם ", "457", ""));
            SystemProductArr.add(new Product(0, "עוגיות שוקולד ציפס, Merba", "יחידה ", "96", ""));
            SystemProductArr.add(new Product(0, "עוגיות שוקולד ציפס, Merba", "100 גרם ", "510", ""));
            SystemProductArr.add(new Product(0, "עוגיית לוטוס", "יחידה", "40", ""));
            SystemProductArr.add(new Product(0, "עוגיית לוטוס אישית", "יחידה", "30", ""));
            SystemProductArr.add(new Product(0, "פתי בר", "יחידה", "35", ""));
            SystemProductArr.add(new Product(0, "בסקוויט", "יחידה", "35", ""));
            SystemProductArr.add(new Product(0, "טיקטק בודד", "יחידה", "2", ""));
            SystemProductArr.add(new Product(0, "טיקטק תפוז", "100 גרם", "399", ""));
            SystemProductArr.add(new Product(0, "טיקטק תות שדה", "100 גרם", "399", ""));
            SystemProductArr.add(new Product(0, "Hit", "יחידה", "61", ""));
            SystemProductArr.add(new Product(0, "Hit", "100 גרם", "508", ""));
            SystemProductArr.add(new Product(0, "וופל חלבה, מן", "יחידה", "31", ""));
            SystemProductArr.add(new Product(0, "וופל חלבה, מן", "100 גרם", "510", ""));
            SystemProductArr.add(new Product(0, "חמצוץ שטוח ,יוגטה", "יחידה", "35", ""));
            SystemProductArr.add(new Product(0, "חמצוץ שטוח, יוגטה", "100 גרם", "373", ""));
            SystemProductArr.add(new Product(0, "גלידה סורבה תות מנגו דל קלוריות", "כדור", "32", ""));
            SystemProductArr.add(new Product(0, "גלידה סורבה תות מנגו דל קלוריות", "100 גרם", "63", ""));
            SystemProductArr.add(new Product(0, "סניידרס שברי בייגלה מחמצת שאור בטעם צ'דר, Snyder's", "100 גרם", "505", "077975095263"));
            SystemProductArr.add(new Product(0, "סניידרס סנדוויץ בייגלה, Snyder's", "יחידה", "15", ""));
            SystemProductArr.add(new Product(0, "סניידרס סנדוויץ בייגלה, Snyder's", "100 גרם", "513", ""));
            SystemProductArr.add(new Product(0, "אובלטים מלוחים", "100 גרם", "350", ""));
            SystemProductArr.add(new Product(0, "נאצוס", "100 גרם", "500", ""));
            SystemProductArr.add(new Product(0, "מיני קצפיות מרנג בטעם פירות יער, אחווה", "יחידה", "3", ""));
            SystemProductArr.add(new Product(0, "מיני קצפיות מרנג בטעם פירות יער, אחווה", "100 גרם", "342", ""));
            SystemProductArr.add(new Product(0, "אפרופו, אסם", "יחידה", "3", ""));
            SystemProductArr.add(new Product(0, "אפרופו, אסם", "שקית 50 גרם", "270", "7290000066332"));
            SystemProductArr.add(new Product(0, "אפרופו, אסם", "100 גרם", "538", "7290106572959 ,7290000066332 "));
            SystemProductArr.add(new Product(0, "סבבה בוטנים אמריקאים", "שקית", "230", "7290010117970"));
            SystemProductArr.add(new Product(0, "סבבה בוטנים אמריקאים", "100 גרם", "461", ""));
            SystemProductArr.add(new Product(0, "דוריטוס גריל, עלית", "יחידה", "8", ""));
            SystemProductArr.add(new Product(0, "דוריטוס גריל, עלית", "שקית 70 גרם", "372", "7290100850923"));
            SystemProductArr.add(new Product(0, "דוריטוס גריל, עלית", "100 גרם", "527", ""));
            SystemProductArr.add(new Product(0, "ביסלי שום, אסם", "100 גרם", "488", "7290115201741"));
            SystemProductArr.add(new Product(0, "דובונים, אסם", "יחידה", "4", ""));
            SystemProductArr.add(new Product(0, "דובונים, אסם", "100 גרם", "534", "7290000066264"));
            SystemProductArr.add(new Product(0, "דובונים בטעם שום בצל, אסם", "יחידה", "4", "7290000062242"));
            SystemProductArr.add(new Product(0, "דובונים בטעם שום בצל, אסם", "100 גרם", "534", "7290000062242"));
            SystemProductArr.add(new Product(0, "סוכריית טופי", "יחידה", "25", ""));
            SystemProductArr.add(new Product(0, "במבה נוגט, אסם", "יחידה", "7", ""));
            SystemProductArr.add(new Product(0, "במבה נוגט, אסם", "100 גרם", "529", "7290100687109"));
            SystemProductArr.add(new Product(0, "במבה אייס קפה, אסם", "יחידה", "8", ""));
            SystemProductArr.add(new Product(0, "במבה אייס קפה", "100 גרם", "535", ""));
            SystemProductArr.add(new Product(0, "ביסלי גריל, אסם", "יחידה", "5", ""));
            SystemProductArr.add(new Product(0, "ביסלי גריל, אסם", "100 גרם", "492", "7290000468747,7290100686171"));
            SystemProductArr.add(new Product(0, "במבה חלבה, אסם", "יחידה", "8", "7290000072067"));
            SystemProductArr.add(new Product(0, "במבה חלבה, אסם", "100 גרם", "529", "7290000072067"));
            SystemProductArr.add(new Product(0, "כיפלי גריל, תלמה", "יחידה", "2", "7290000110844"));
            SystemProductArr.add(new Product(0, "כיפלי גריל, תלמה", "100 גרם", "527", "7290000110844"));
            SystemProductArr.add(new Product(0, "תפוצ'יפס קידס, עלית", "100 גרם", "492", "7290101551584 , 7290104068676"));
            SystemProductArr.add(new Product(0, "ביסלי שום בצל-מהדורה מוגבלת, אסם", "יחידה", "8", ""));
            SystemProductArr.add(new Product(0, "ביסלי שום בצל-מהדורה מוגבלת, אסם", "100 גרם", "515", "7290112962522"));
            SystemProductArr.add(new Product(0, "במבה, אסם", "100 גרם", "534", ""));
            SystemProductArr.add(new Product(0, "תפוציפס קראנצ' בטעם מקסיקני, עלית", "100 גרם", "539", "7290102030330"));
            SystemProductArr.add(new Product(0, "ציפס בטעם טבעי אסם chips classic, אסם", "100 גרם", "534", "7290118422525"));
            SystemProductArr.add(new Product(0, "חלווה בטעם שוקו וניל ,אחווה", "יחידה", "284", "7290010328765"));
            SystemProductArr.add(new Product(0, "חלווה בטעם שוקו וניל ,אחווה", "100 גרם", "567", "7290010328765"));
            SystemProductArr.add(new Product(0, "מיני פינוקיות בטעם טופי קרמל מלוח, עלית", "יחידה", "46", "7290115671346"));
            SystemProductArr.add(new Product(0, "מיני פינוקיות בטעם טופי קרמל מלוח, עלית", "100 גרם", "508", "7290115671346"));

        }
        //שילובים, מאכלים, עברו שינוי וכו
        if (0 == 0) {
            SystemProductArr.add(new Product(0, "סיגר תפוח אדמה", "יחידה", "61", ""));
            SystemProductArr.add(new Product(0, "סיגר תפוח אדמה", "100 גרם", "213", ""));
            SystemProductArr.add(new Product(0, "מרק ירקות", "מנה", "130", ""));
            SystemProductArr.add(new Product(0, "מרק ירקות", "100 גרם", "35", ""));
            SystemProductArr.add(new Product(0, "קוסקוס בסגנון ים תיכוני מוכן, שופרסל", "100 גרם", "139", "7296073552987"));
            SystemProductArr.add(new Product(0, "קוסקוס בסגנון ים תיכוני לא מוכן, שופרסל", "100 גרם", "368", "7296073552987"));
            SystemProductArr.add(new Product(0, "מנת הבית תבשיל אורז בסגנון אושפלו, טעים", "יחידה", "365", "7290018195512"));
            SystemProductArr.add(new Product(0, "מנת הבית תבשיל אורז בסגנון אושפלו, טעים", "100 גרם", "146", ""));
            SystemProductArr.add(new Product(0, "קובה בורגול בשר מטוגנת", "100 גרם", "270", ""));
            SystemProductArr.add(new Product(0, "מרק עדשים", "100 גרם", "80", ""));
            SystemProductArr.add(new Product(0, "פיתה עם זעתר", "יחידה", "420", ""));
            SystemProductArr.add(new Product(0, "סופיריטה", "100 גרם", "230", ""));
            SystemProductArr.add(new Product(0, "קובה סלק במילוי אגוזים", "יחידה", "140", ""));
            SystemProductArr.add(new Product(0, "חמין", "100 גרם", "150", ""));
            SystemProductArr.add(new Product(0, "מרק בצל", "100 גרם", "85", ""));
            SystemProductArr.add(new Product(0, "עוגיות קעקעת", "יחידה", "140", ""));
            SystemProductArr.add(new Product(0, "עוגיות קעקעת", "יחידה קטנה", "70", ""));
            SystemProductArr.add(new Product(0, "עוגת סולת בסבוסה", "100 גרם", "280", ""));
            SystemProductArr.add(new Product(0, "פלאפל", "מנה", "800", ""));
            SystemProductArr.add(new Product(0, "אורז עם גזר וצימוקים", "100 גרם", "95", ""));
            SystemProductArr.add(new Product(0, "בורקס גבינה מדפי אורז", "יחידה", "55", ""));
            SystemProductArr.add(new Product(0, "אגרול אפוי", "100 גרם", "146", ""));
            SystemProductArr.add(new Product(0, "שניצל פירורים אפוי", "100 גרם", "200", ""));
            SystemProductArr.add(new Product(0, "רוזלח תמרים", "יחידה", "150", ""));
            SystemProductArr.add(new Product(0, "רוזלח תמרים", "100 גרם", "380", ""));
            SystemProductArr.add(new Product(0, "טבעת בצל", "יחידה", "25", ""));
            SystemProductArr.add(new Product(0, "טבעות בצל", "100 גרם", "230", ""));
            SystemProductArr.add(new Product(0, "קציצת המבורגר", "100 גרם", "240", ""));
            SystemProductArr.add(new Product(0, "לחמניית המבורגר", "יחידה", "240", ""));
            SystemProductArr.add(new Product(0, "לחמניית המבורגר", "100 גרם", "280", ""));
            SystemProductArr.add(new Product(0, "נאגטס ירקות לבנים, טבעול", "יחידה", "38", ""));
            SystemProductArr.add(new Product(0, "נאגטס ירקות לבנים, טבעול", "100 גרם", "172", ""));
            SystemProductArr.add(new Product(0, "לקט נורמנדי, סנפרוסט", "100 גרם", "23", ""));
            SystemProductArr.add(new Product(0, "כרובית ברוקולי וגזר בתנור", "100 גרם", "30", ""));
            SystemProductArr.add(new Product(0, "אורז עם גרגירי חומוס וגזר", "100 גרם", "120", ""));
            SystemProductArr.add(new Product(0, "טונה בשמן, פילטונה", "קופסאת שימורים", "175", ""));
            SystemProductArr.add(new Product(0, "טונה בשמן, פילטונה", "קופסאת שימורים 112", "175", ""));
            SystemProductArr.add(new Product(0, "טונה בשמן, פילטונה", "100 גרם", "156", ""));
            SystemProductArr.add(new Product(0, "אפונה וגזר תבשיל", "כף", "9", ""));
            SystemProductArr.add(new Product(0, "אפונה וגזר תבשיל", "100 גרם", "35", ""));
            SystemProductArr.add(new Product(0, "בננה מטוגנת", "יחידה", "200", ""));
            SystemProductArr.add(new Product(0, "כדור עוף חמוץ מתוק", "יחידה", "150", ""));
            SystemProductArr.add(new Product(0, "אגרול מטוגן במילוי ירקות", "יחידה", "250", ""));
            SystemProductArr.add(new Product(0, "שווארמה בלאפה +סלטים וממרחים", "יחידה", "1000", ""));
            SystemProductArr.add(new Product(0, "שווארמה בפיתה +סלטים וממרחים", "יחידה", "700", ""));
            SystemProductArr.add(new Product(0, "שווארמה בצלחת", "יחידה", "500", ""));
            SystemProductArr.add(new Product(0, "כריך טוניסאי, משהו משהו", "יחידה", "448", ""));
            SystemProductArr.add(new Product(0, "כריך טוניסאי, משהו משהו", "100 גרם", "249", ""));
            SystemProductArr.add(new Product(0, "דגני בוקר שקדים ודבש פיטנס", "חופן", "30", ""));
            SystemProductArr.add(new Product(0, " דגני בוקר שקדים ודבש פיטנס ", "מנה", "116", ""));
            SystemProductArr.add(new Product(0, " דגני בוקר שקדים ודבש פיטנס", "100 גרם", "386", ""));
            SystemProductArr.add(new Product(0, "לוביה מבושלת", "100 גרם", "116", ""));
            SystemProductArr.add(new Product(0, "קבוקים עם שומשום", "יחידה", "12", ""));
            SystemProductArr.add(new Product(0, "קבוקים עם שומשום", "100 גרם", "450", ""));
            SystemProductArr.add(new Product(0, " גרעיני חמנייה", "חופן", "60", ""));
            SystemProductArr.add(new Product(0, " גרעיני חמנייה", "100 גרם", "620", ""));
            SystemProductArr.add(new Product(0, "מיני ניוקי תפוח אדמה", "יחידה", "5", ""));
            SystemProductArr.add(new Product(0, "מיני ניוקי תפוח אדמה", "100 גרם", "160", ""));
            SystemProductArr.add(new Product(0, "פירה", "100 גרם", "85", ""));
            SystemProductArr.add(new Product(0, "תפוח אדמה אפוי", "100 גרם", "95", ""));
            SystemProductArr.add(new Product(0, "חביתה, 2 ביצים", "יחידה", "230", ""));
            SystemProductArr.add(new Product(0, "תמר ואגוז", "יחידה", "75", ""));
            SystemProductArr.add(new Product(0, "חומוס אחלה", "כף", "28", ""));
            SystemProductArr.add(new Product(0, "חומוס אחלה", "100 גרם", "186", ""));
            SystemProductArr.add(new Product(0, "חומוס ביתי ", "כף", "70", ""));
            SystemProductArr.add(new Product(0, "חומוס ביתי ", "כפית", "30", ""));
            SystemProductArr.add(new Product(0, "חומוס ביתי ", "100 גרם", "180", ""));
            SystemProductArr.add(new Product(0, "סלט ירקות", "100 גרם", "16", ""));
            SystemProductArr.add(new Product(0, "סוכר", "כפית", "20", ""));
            SystemProductArr.add(new Product(0, "סוכר", "100 גרם", "387", ""));
            SystemProductArr.add(new Product(0, "אננס חתוך מוקפא", "100 גרם", "53", ""));
            SystemProductArr.add(new Product(0, "מנגו חתוך מוקפא", "100 גרם", "62", ""));
            SystemProductArr.add(new Product(0, "תערובת אסייתית, סנפרוסט", "100 גרם", "32", ""));
            SystemProductArr.add(new Product(0, "פנקייק", "100 גרם", "230", ""));
            SystemProductArr.add(new Product(0, "כרובית בתנור", "100 גרם", "35", ""));
            SystemProductArr.add(new Product(0, "פסטה עם טונה- עץ הזית", "100 גרם", "220", ""));
            SystemProductArr.add(new Product(0, "עוגת שוקולד", "כפית", "45", ""));
            SystemProductArr.add(new Product(0, "עוגת שוקולד", "100 גרם", "370", ""));
            SystemProductArr.add(new Product(0, "קרואסון שקדים", "יחידה גדולה", "610", ""));
            SystemProductArr.add(new Product(0, "קרואסון שקדים שוקולד", "יחידה גדולה", "690", ""));
            SystemProductArr.add(new Product(0, "רוגלך", "יחידה", "200", ""));
            SystemProductArr.add(new Product(0, "רוגלך", "100 גרם", "450", ""));
            SystemProductArr.add(new Product(0, "מאפה דניש קינמון", "יחידה", "520", ""));
            SystemProductArr.add(new Product(0, "מאפה קינמון", "יחידה קטנה", "180", ""));
            SystemProductArr.add(new Product(0, "פאי גבינה ותפוחים", "יחידה גדולה", "620", ""));
            SystemProductArr.add(new Product(0, "עוגיית מאפה חלבה", "יחידה", "500", ""));
            SystemProductArr.add(new Product(0, "עוגיית מאפה תמרים", "יחידה", "420", ""));
            SystemProductArr.add(new Product(0, "עוגיית בראוניז", "יחידה", "350", ""));
            SystemProductArr.add(new Product(0, "עוגיית בראוניז", "100 גרם", "400", ""));
            SystemProductArr.add(new Product(0, "שטרודל תפוחי עץ", "יחידה", "240", ""));
            SystemProductArr.add(new Product(0, "מאפה פילו תפוחים", "יחידה", "220", ""));
            SystemProductArr.add(new Product(0, "מאפה פילו גבינה", "יחידה", "220", ""));
            SystemProductArr.add(new Product(0, "שמרים גבינה תפוחים", "יחידה", "400", ""));
            SystemProductArr.add(new Product(0, "גבינית", "יחידה קטנה", "280", ""));
            SystemProductArr.add(new Product(0, "עוגת גבינה קלאסית", "100 גרם", "340", ""));
            SystemProductArr.add(new Product(0, "מאפה בולגרית", "יחידה", "520", ""));
            SystemProductArr.add(new Product(0, "קרואסון חמאה", "יחידה", "390", ""));
            SystemProductArr.add(new Product(0, "קרואסון שוקולד", "יחידה", "500", ""));
            SystemProductArr.add(new Product(0, "קרואסון שוקולד", "100 גרם", "550", ""));
            SystemProductArr.add(new Product(0, "בורקס גבינה בולגרית (50 גרם)", "יחידה", "145", ""));
            SystemProductArr.add(new Product(0, "בורקס גבינה בולגרית", "יחידה גדולה", "490", ""));
            SystemProductArr.add(new Product(0, "בורקס גבינה בולגרית", "100 גרם", "285", ""));
            SystemProductArr.add(new Product(0, "בורקס בשר", "100 גרם", "250", ""));
            SystemProductArr.add(new Product(0, "בורקס פיצה (50 גרם)", "יחידה", "150", ""));
            SystemProductArr.add(new Product(0, "בורקס תפוח אדמה (50 גרם)", "יחידה", "150", ""));
            SystemProductArr.add(new Product(0, "בורקס תפוח אדמה", "100 גרם", "280", ""));
            SystemProductArr.add(new Product(0, "בורקס פטריות (50 גרם)", "יחידה", "150", ""));
            SystemProductArr.add(new Product(0, "בורקס תרד (50 גרם)", "יחידה", "150", ""));
            SystemProductArr.add(new Product(0, "בורקס טונה (50 גרם)", "יחידה", "145", ""));
            SystemProductArr.add(new Product(0, "מלווח/מלאווח/ מלוואח", "יחידה", "410", ""));
            SystemProductArr.add(new Product(0, "מלווח/מלאווח/ מלוואח", "100 גרם", "350", ""));
            SystemProductArr.add(new Product(0, "סלופי גו", "יחידה", "500", ""));
            SystemProductArr.add(new Product(0, "בורגול וגרגירי חומוס עם טונה, עץ הזית", "100 גרם", "180", "7290017142487"));
            SystemProductArr.add(new Product(0, "קינואה לבנה ואדומה עם טונה, עץ הזית", "יחידה 160 גרם", "263", "7290017142401"));
            SystemProductArr.add(new Product(0, "קינואה לבנה ואדומה עם טונה, עץ הזית", "100 גרם", "160", "7290017142401"));
            SystemProductArr.add(new Product(0, "פסטה עם טונה, עץ הזית", "100 גרם", "219", "7290017142395"));
            SystemProductArr.add(new Product(0, "מיקס טו גו פתיתים וירקות עם טונה, StarKist", "100 גרם", "181", "7290017617091"));
            SystemProductArr.add(new Product(0, "מיקס טו גו 4 דגנים וירקות עם טונה, StarKist", "100 גרם", "217", "7290017617107"));
            SystemProductArr.add(new Product(0, "ירקות גינה עם טונה ,וילי פוד", "100 גרם", "132", "7290108507942"));
            SystemProductArr.add(new Product(0, "קינואה עם טונה וירקות, וילי פוד", "100 גרם", "202", "7290108507911"));
            SystemProductArr.add(new Product(0, "ארוחת נודלס בטעם ירקות, מג'יק יבש", "100 גרם", "416", ""));
            SystemProductArr.add(new Product(0, "תבשיל אישי נודלס בטעם פיקנטי, סוגת", "אריזה 65 גרם", "80", ""));
            SystemProductArr.add(new Product(0, "תבשיל אישי נודלס בטעם פיקנטי, סוגת", "100 גרם", "452", ""));
            SystemProductArr.add(new Product(0, "תבשיל אישי נודלס בטעם פיקנטי (לאחר הכנה), סוגת", "100 גרם", "80", ""));
            SystemProductArr.add(new Product(0, "פסטה ברוטב עגבניות", "100 גרם", "139", ""));
            SystemProductArr.add(new Product(0, "פריטטה תרד 2 ביצים", "יחידה", "330", ""));
            SystemProductArr.add(new Product(0, "חציל מטוגן", "פרוסה", "50", ""));
            SystemProductArr.add(new Product(0, "אננס מיובש", "פרוסה", "100", ""));
            SystemProductArr.add(new Product(0, "אננס מיובש", "100 גרם", "335", ""));
            SystemProductArr.add(new Product(0, "משמש מיובש", "יחידה", "25", ""));
            SystemProductArr.add(new Product(0, "משמש מיובש", "100 גרם", "240", ""));
            SystemProductArr.add(new Product(0, "אינסטנט פודינג בטעם וניל , אסם", "שקית 80 גרם", "300", ""));
            SystemProductArr.add(new Product(0, "איסטנט פודינג בטעם וניל, אסם", "100 גרם", "372", ""));

        }
        //משקאות
        if (0 == 0) {

            SystemProductArr.add(new Product(0, "יין אדום", "100 גרם", "85", ""));
            SystemProductArr.add(new Product(0, "מיץ אננס בננה , ספרינג", "כוס", "75", "7290019056652"));
            SystemProductArr.add(new Product(0, "מיץ אננס בננה , ספרינג", "100 מל", "42", "7290019056652"));
            SystemProductArr.add(new Product(0, "חלב סויה", "100 מל", "54", ""));
            SystemProductArr.add(new Product(0, "חלב סויה וניל", "100 מל", "49", ""));
            SystemProductArr.add(new Product(0, "מיץ ענבים", "100 מל", "60", ""));
            SystemProductArr.add(new Product(0, "מים", "כוס", "0", ""));
            SystemProductArr.add(new Product(0, "קולה", "פחית 330 מל", "125", "7290011017866,7290001594056"));
            SystemProductArr.add(new Product(0, "קולה", "100 מל", "42", "7290110115203"));
            SystemProductArr.add(new Product(0, "קולה זירו", "פחית 330 מל", "1", "7290011017873"));
            SystemProductArr.add(new Product(0, "קולה זירו", "100 מל", "0.3", "7290013585387"));
            SystemProductArr.add(new Product(0, "מיץ אננס", "כוס", "110", ""));
            SystemProductArr.add(new Product(0, "מיץ אננס", "100 מל", "60", ""));
            SystemProductArr.add(new Product(0, "ספרייט ליים זירו", "פחית 330 מל", "3", ""));
            SystemProductArr.add(new Product(0, "ספרייט ליים זירו", "100 מל", "0.9", ""));
            SystemProductArr.add(new Product(0, "אננס בננה כורכום, Fruit &Veg", "100 מל", "42", ""));
            SystemProductArr.add(new Product(0, "אננס בננה כורכום, Fruit &Veg", "100 מל", "42", ""));
            SystemProductArr.add(new Product(0, "אננס בננה כורכום, Fruit &Veg", "100 מל", "42", ""));
            SystemProductArr.add(new Product(0, "תפוח בננה מלון נענע, Fruit &Veg", "100 מל", "40", ""));
            SystemProductArr.add(new Product(0, "אננס תפוח גזר, Fruit &Veg", "100 מל", "41", ""));
            SystemProductArr.add(new Product(0, "תפוח סלק רימון ג'ינג'ר, Fruit &Veg", "100 מל", "39", ""));
            SystemProductArr.add(new Product(0, "שוקו בשקית, יטבתה", "יחידה", "110", ""));
            SystemProductArr.add(new Product(0, "שוקו בשקית, יטבתה", "100 מל", "49", ""));
            SystemProductArr.add(new Product(0, "אקטימל תות, שטראוס", "100 מל", "52", ""));
            SystemProductArr.add(new Product(0, "ברד", "כוס", "200", ""));
            SystemProductArr.add(new Product(0, "7up", "100 מל", "44", "7290000136172"));
            SystemProductArr.add(new Product(0, "סודה שוופס ליים מוגז עדין בטעם לייט, schweppes", "100 מל", "20", "7290019056058"));
            SystemProductArr.add(new Product(0, "סודה שוופס פירות יער מוגז עדין בטעם פירות יער, schweppes", "100 מל", "20", "7290019056065"));
            SystemProductArr.add(new Product(0, "שמן קנולה מזוכך, מילומור", "100 מל", "828", "7290002374312"));

        }
        //רטבים/ ממרחים
        if (0 == 0) {
            SystemProductArr.add(new Product(0, "קצפת", "כפית", "50", ""));
            SystemProductArr.add(new Product(0, "קצפת", "100 גרם", "200", ""));
            SystemProductArr.add(new Product(0, "ריבת תות", "כפית", "38", ""));
            SystemProductArr.add(new Product(0, "ריבת תות", "כף", "83", ""));
            SystemProductArr.add(new Product(0, "ריבת תות", "100 גרם", "260", ""));
            SystemProductArr.add(new Product(0, "רוטב טריאקי", "כף", "30", ""));
            SystemProductArr.add(new Product(0, "רוטב טריאקי", "כפית", "15", ""));
            SystemProductArr.add(new Product(0, "רוטב טריאקי", "100 גרם", "296", ""));
            SystemProductArr.add(new Product(0, "מיונז", "כפית", "30", ""));
            SystemProductArr.add(new Product(0, "מיונז", "כף", "90", ""));
            SystemProductArr.add(new Product(0, "מיונז", "100 גרם", "600", ""));
            SystemProductArr.add(new Product(0, "קטשופ היינץ Heinz", "שפריץ / שליכטה", "10", "8715700419732 , 8715700419718"));
            SystemProductArr.add(new Product(0, "קטשופ היינץ Heinz", "100 גרם", "102", "8715700419732 , 8715700419718"));
            SystemProductArr.add(new Product(0, "קטשופ אסם", "100 גרם", "112", "7290000072623"));
            SystemProductArr.add(new Product(0, "רוטב אדום חמוץ מתוק", "כף", "60", ""));
            SystemProductArr.add(new Product(0, "חמאת בוטנים", "כפית", "43", ""));
            SystemProductArr.add(new Product(0, "חמאת בוטנים", "100 גרם", "530", ""));
            SystemProductArr.add(new Product(0, "חמאת בוטנים סקיפי, Skippy", "כפית", "50", "37600207188"));
            SystemProductArr.add(new Product(0, "חמאת בוטנים סקיפי, Skippy", "100 גרם", "626", "37600207188"));
            SystemProductArr.add(new Product(0, " ממרח נוטלה, נוטלה", "כפית", "90", "80177173"));
            SystemProductArr.add(new Product(0, "ממרח נוטלה, נוטלה", "כף", "250", "80177173"));
            SystemProductArr.add(new Product(0, "ממרח נוטלה, נוטלה", "100 גרם", "539", "80177173"));
            SystemProductArr.add(new Product(0, "ממרח שוקולד השחר, השחר העולה", "כפית", "90", "7290000416021,7290000416045"));
            SystemProductArr.add(new Product(0, "ממרח שוקולד השחר, השחר העולה", "כף", "230", "7290000416021,7290000416045"));
            SystemProductArr.add(new Product(0, "ממרח שוקולד השחר, השחר העולה", "100 גרם", "504", "7290000416021,7290000416045"));
            SystemProductArr.add(new Product(0, "ממרח שוקולד השחר פרווה, השחר העולה", "כפית", "90", "7290000416618 , 7290000416632"));
            SystemProductArr.add(new Product(0, "ממרח שוקולד השחר פרווה, השחר העולה", "כף", "235", "7290000416618 , 7290000416632"));
            SystemProductArr.add(new Product(0, "ממרח שוקולד השחר פרווה, השחר העולה", "100 גרם", "502", "7290000416618 , 7290000416632"));
            SystemProductArr.add(new Product(0, "ממרח אגוזים השחר, השחר העולה", "כפית", "95", ""));
            SystemProductArr.add(new Product(0, "ממרח אגוזים השחר, השחר העולה", "כף", "250", ""));
            SystemProductArr.add(new Product(0, "ממרח אגוזים השחר, השחר העולה", "100 גרם", "533", ""));
            SystemProductArr.add(new Product(0, "פסטו", "כפית", "40", ""));
            SystemProductArr.add(new Product(0, "פסטו", "כף", "90", ""));
            SystemProductArr.add(new Product(0, "פסטו", "100 גרם", "468", ""));
            SystemProductArr.add(new Product(0, "סילאן", "כף", "60", ""));
            SystemProductArr.add(new Product(0, "סילאן", "כפית", "30", ""));
            SystemProductArr.add(new Product(0, "סילאן", "100 גרם", "305", ""));
            SystemProductArr.add(new Product(0, "דבש", "כף", "60", ""));
            SystemProductArr.add(new Product(0, "דבש", "כפית", "30", ""));
            SystemProductArr.add(new Product(0, "דבש", "100 גרם", "305", ""));
            SystemProductArr.add(new Product(0, "טחינה", "כף", "50", ""));
            SystemProductArr.add(new Product(0, "טחינה", "100 גרם", "300", ""));
            SystemProductArr.add(new Product(0, "טחינה גולמית", "כף", "105", ""));
            SystemProductArr.add(new Product(0, "טחינה גולמית", "100 גרם", "620", ""));
            SystemProductArr.add(new Product(0, "שמן זית", "כף", "90", ""));
            SystemProductArr.add(new Product(0, "שמן זית", "כפית", "45", ""));
            SystemProductArr.add(new Product(0, "שמן זית", "פקק", "40", ""));
            SystemProductArr.add(new Product(0, "שמן זית", "100 גרם", "884", ""));
            SystemProductArr.add(new Product(0, "שמן קנולה", "כף", "90", ""));
            SystemProductArr.add(new Product(0, "שמן קנולה", "כפית", "45", ""));
            SystemProductArr.add(new Product(0, "שמן קנולה", "100 גרם", "884", ""));
            SystemProductArr.add(new Product(0, "שמן קוקוס", "כף", "85", ""));
            SystemProductArr.add(new Product(0, "שמן קוקוס", "כפית", "43", ""));
            SystemProductArr.add(new Product(0, "שמן קוקוס", "100 גרם", "862", ""));
            SystemProductArr.add(new Product(0, "שמן שומשום", "כף", "90", ""));
            SystemProductArr.add(new Product(0, "שמן שומשום", "כפית", "45", ""));
            SystemProductArr.add(new Product(0, "שמן שומשום", "100 גרם", "884", ""));
            SystemProductArr.add(new Product(0, "שמן תירס", "כף", "90", ""));
            SystemProductArr.add(new Product(0, "שמן תירס", "כפית", "45", ""));
            SystemProductArr.add(new Product(0, "שמן תירס", "100 גרם", "884", ""));
            SystemProductArr.add(new Product(0, "חומץ טבעי משומר 5%, יכין", "100 מל", "12", ""));

        }
        //אבקות / תבלינים / זרעים
        if (0 == 0) {
            SystemProductArr.add(new Product(0, "זרעי ציה", "כפית", "33", ""));
            SystemProductArr.add(new Product(0, "זרעי ציה", "כף", "65", ""));
            SystemProductArr.add(new Product(0, "זרעי ציה", "100 גרם", "524", ""));
            SystemProductArr.add(new Product(0, "קמח תופח", "100 גרם", "337", ""));
            SystemProductArr.add(new Product(0, "קמח כוסמין מלא", "100 גרם", "382", ""));
            SystemProductArr.add(new Product(0, "שיבולת שועל", "כפית", "20", ""));
            SystemProductArr.add(new Product(0, "שיבולת שועל", "כף", "40", ""));
            SystemProductArr.add(new Product(0, "שיבולת שועל", "חופן", "70", ""));
            SystemProductArr.add(new Product(0, "שיבולת שועל", "100 גרם", "389", ""));
            SystemProductArr.add(new Product(0, "שוקולית", "כפית", "16", ""));
            SystemProductArr.add(new Product(0, "שוקולית", "כף", "48", ""));
            SystemProductArr.add(new Product(0, "שוקולית", "100 גרם", "400", "7290000174723"));
            SystemProductArr.add(new Product(0, "שוקולית לאפייה", "כפית", "15", ""));
            SystemProductArr.add(new Product(0, "שוקולית לאפייה", "כף", "40", ""));
            SystemProductArr.add(new Product(0, "שוקולית לאפייה", "100 גרם", "399", "7290106525320"));
            SystemProductArr.add(new Product(0, "קפה נמס, עלית", "100 גרם", "1.7", ""));
            SystemProductArr.add(new Product(0, "קמח תפוח אדמה", "כפית", "22", ""));
            SystemProductArr.add(new Product(0, "קמח תפוח אדמה", "100 גרם", "357", ""));
            SystemProductArr.add(new Product(0, "אבקת אפייה", "כף", "5", ""));
            SystemProductArr.add(new Product(0, "אבקת אפייה", "כפית", "3", ""));
            SystemProductArr.add(new Product(0, "אבקת אפייה", "100 גרם", "53", ""));
            SystemProductArr.add(new Product(0, "אבקת סוכר", "כף", "60", ""));
            SystemProductArr.add(new Product(0, "אבקת סוכר", "כפית", "20", ""));
            SystemProductArr.add(new Product(0, "אבקת סוכר", "100 גרם", "390", ""));
            SystemProductArr.add(new Product(0, "אבקת קארי", "100 גרם", "325", ""));
            SystemProductArr.add(new Product(0, "מרק ירקות נמס בכוס קנור , knorr", "100 גרם", "391", "7290112493293"));
            SystemProductArr.add(new Product(0, "מרק ירקות נמס בכוס קנור , knorr", "100 מל", "43", "7290112493293"));
            SystemProductArr.add(new Product(0, "מרק עגבניות נמס בכוס קנור , knorr", "100 מל", "48", "7290000169538"));
            SystemProductArr.add(new Product(0, "מרק עגבניות נמס בכוס קנור , knorr", "100 גרם", "343", "7290000169538"));
        }
        //GO%PRO מועשר חלבון
        if (0 == 0) {


            SystemProductArr.add(new Product(0, "יוגורט פירות יער במרקם סמיך 20 גרם חלבון , יופלה Go", "גביע 200 גרם", "109", ""));
            SystemProductArr.add(new Product(0, "יוגורט פירות יער במרקם סמיך 20 גרם חלבון, יופלה Go", "100 גרם", "55", ""));
            SystemProductArr.add(new Product(0, "יוגורט דובדבן במרקם סמיך 20 גרם חלבון, יופלה Go", "גביע 200 גרם", "111", ""));
            SystemProductArr.add(new Product(0, "יוגורט דובדבן במרקם סמיך 20 גרם חלבון, יופלה Go", "100 גרם", "56", ""));
            SystemProductArr.add(new Product(0, "יוגורט קוקוס במרקם סמיך 20 גרם חלבון, יופלה Go", "גביע 200 גרם", "115", ""));
            SystemProductArr.add(new Product(0, "יוגורט קוקוס במרקם סמיך 20 גרם חלבון, יופלה Go", "100 גרם", "58", ""));
            SystemProductArr.add(new Product(0, "יוגורט בננה קרמל במרקם סמיך 20 גרם חלבון, יופלה Go", "גביע 200 גרם", "108", ""));
            SystemProductArr.add(new Product(0, "יוגורט בננה קרמל במרקם סמיך 20 גרם חלבון, יופלה Go", "100 גרם", "54", ""));
            SystemProductArr.add(new Product(0, "יוגורט אפרסק במרקם סמיך 20 גרם חלבון, יופלה Go", "גביע 200 גרם", "109", ""));
            SystemProductArr.add(new Product(0, "יוגורט אפרסק במרקם סמיך 20 גרם חלבון, יופלה Go", "100 גרם", "55", ""));
            SystemProductArr.add(new Product(0, "יוגורט תות במרקם סמיך 20 גרם חלבון, יופלה Go", "גביע 200 גרם", "108", ""));
            SystemProductArr.add(new Product(0, "יוגורט תות במרקם סמיך 20 גרם חלבון, יופלה Go", "100 גרם", "54", ""));
            SystemProductArr.add(new Product(0, "יוגורט טבעי  20 גרם חלבון, יופלה Go", "100 גרם", "72", ""));
            SystemProductArr.add(new Product(0, "יוגורט במתיקות מעודנת 20 גרם חלבון, יופלה Go", "100 גרם", "91", ""));
            SystemProductArr.add(new Product(0, "יוגורט אפרסק 20 גרם חלבון, יופלה Go", "100 גרם", "98", ""));
            SystemProductArr.add(new Product(0, "יוגורט פירות יער 20 גרם חלבון, יופלה Go", "100 גרם", "98", ""));
            SystemProductArr.add(new Product(0, "יוגורט תות 20 גרם חלבון, יופלה Go", "100 גרם", "98", ""));
            SystemProductArr.add(new Product(0, "יוגורט אננס 20 גרם חלבון, יופלה Go לייט", "100 גרם", "61", ""));
            SystemProductArr.add(new Product(0, "יוגורט אפרסק 20 גרם חלבון, יופלה Go לייט", "100 גרם", "59", ""));
            SystemProductArr.add(new Product(0, "יוגורט דובדבן 20 גרם חלבון, יופלה Go לייט", "100 גרם", "60", ""));
            SystemProductArr.add(new Product(0, "משקה חלב בטעם עוגיות 27 גרם חלבון, תנובה GO", "יחידה", "272", "7290110329686"));
            SystemProductArr.add(new Product(0, "משקה חלב בטעם עוגיות 27 גרם חלבון, תנובה GO", "100 מל", "80", ""));
            SystemProductArr.add(new Product(0, "משקה אייס קפה 27 גרם חלבון, תנובה GO", "100 מל", "82", "7290110325893"));
            SystemProductArr.add(new Product(0, "משקה יוגורט בננה ואפרסק 20 גרם חלבון, יופלה GO", "100 מל", "74", ""));
            SystemProductArr.add(new Product(0, "משקה יוגורט תות ופטל 20 גרם חלבון, יופלה GO", "יחידה", "198", "7290110323073"));
            SystemProductArr.add(new Product(0, "משקה יוגורט תות ופטל 20 גרם חלבון, יופלה GO", "100 מל", "79", "7290110323073"));
            SystemProductArr.add(new Product(0, "משקה יוגורט תות ובננה 20 גרם חלבון, יופלה GO לייט", "100 מל", "51", ""));
            SystemProductArr.add(new Product(0, "משקה יוגורט מנגו ואננס 20 גרם חלבון, יופלה GO לייט", "100 מל", "51", ""));
            SystemProductArr.add(new Product(0, "משקה סויה קפה 20 גרם חלבון, תנובה GO", "100 מל", "79", ""));
            SystemProductArr.add(new Product(0, "משקה סויה אגוזי לוז 20 גרם חלבון, תנובה GO", "100 מל", "79", ""));
            SystemProductArr.add(new Product(0, "משקה סויה במתיקות מעודנת מועשר בחלבון, תנובה GO", "100 מל", "62", ""));
            SystemProductArr.add(new Product(0, "מעדן סויה תות 20 גרם חלבון, תנובה GO", "100 גרם", "95", ""));
            SystemProductArr.add(new Product(0, "מעדן סויה קוקוס 20 גרם חלבון, תנובה GO", "100 גרם", "95", ""));
            SystemProductArr.add(new Product(0, "מעדן חלב בטעם שוקולד 12 גרם חלבון, תנובה GO", "100 גרם", "107", ""));
            SystemProductArr.add(new Product(0, "מעדן חלב בטעם וניל 12 גרם חלבון, תנובה GO", "100 גרם", "106", ""));
            SystemProductArr.add(new Product(0, "מעדן חלב בטעם קרמל מלוח 12 גרם חלבון, תנובה GO", "100 גרם", "108", ""));
            SystemProductArr.add(new Product(0, "מעדן pro 11 גרם חלבון מעדן חלב מועשר בטעם וניל, שטראוס", "גביע", "146", "7290110571382"));
            SystemProductArr.add(new Product(0, "מעדן pro 11 גרם חלבון מעדן חלב מועשר בטעם וניל, שטראוס", "100 גרם", "97", "7290110571382"));
            SystemProductArr.add(new Product(0, "אבקת חלב", "כפית", "30", ""));
            SystemProductArr.add(new Product(0, "אבקת חלב", "100 גרם", "500", ""));
            SystemProductArr.add(new Product(0, "חטיף חלבון GO בצק עוגיות", "יחידה", "222", ""));
            SystemProductArr.add(new Product(0, "חטיף חלבון GO בצק עוגיות", "100 גרם", "370", ""));
            SystemProductArr.add(new Product(0, "Go חטיף חלבון בטעם קרמל מלוח וחמאת בוטנים", "יחידה", "235", "7290116930015"));
            SystemProductArr.add(new Product(0, "Go חטיף חלבון בטעם קרמל מלוח וחמאת בוטנים", "100 גרם", "392", "7290116930015"));
            SystemProductArr.add(new Product(0, "משקה קפה חלבון 25 Pro", "יחידה", "228", ""));
            SystemProductArr.add(new Product(0, "משקה קפה חלבון 25 Pro", "100 מל", "65", ""));
            SystemProductArr.add(new Product(0, "חטיף חלבון פראוד קשיו קרמל", "יחידה", "211", ""));
            SystemProductArr.add(new Product(0, "חטיף חלבון פראוד קשיו קרמל", "100 גרם", "352", ""));
            SystemProductArr.add(new Product(0, "משקה מנגו אננס 20 Go", "100 מל", "51", ""));
            SystemProductArr.add(new Product(0, "חטיף חלבון בטעם חמאת בוטנים, allin", "יחידה", "199", ""));
            SystemProductArr.add(new Product(0, "נייצר ואלי חטיף פרוטאין בוטנים עם ציפוי קרמל מלוח, Nature valley", "יחידה", "200", "8410076900333,8410076610386"));
            SystemProductArr.add(new Product(0, "נייצר ואלי חטיף פרוטאין בוטנים עם ציפוי קרמל מלוח, Nature valley", "100 גרם", "500", "8410076900333,8410076610386"));
        }
        }

    public static  ArrayList<Product> getSystemProductsArr() {
        makeTheList();
        return SystemProductArr ;
    }

    private void clipExampleListAsCode(String labal , Context context){
        String detailsString=""+labal+"";
        detailsString=detailsString+" "+SystemProductArr.size()+" items ";
        for(int i=0; i <SystemProductArr.size();i++){
            String itemT= "SystemProductArr.add(new ExampleItem("+0+","+0+","+"\""+ SystemProductArr.get( i ).getName()+"\"" +","+"\""+ SystemProductArr.get( i ).getUnit()+"\""+" ,"+"\""+ SystemProductArr.get( i ).getCalorieText()+"\""+","+0+","+"null"+"));";
            detailsString=detailsString.toString()+ "\n"+itemT;
        }
        clipData(detailsString , context );
        makeToast("ההעתקה בוצעה בהצלחה" ,  context );
    }
}
